"""empty message

Revision ID: 2e5dd72ac8e4
Revises: 
Create Date: 2018-09-30 15:38:13.344401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5dd72ac8e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('type', sa.String(length=255), nullable=False))
    op.drop_constraint('products_quantity_key', 'products', type_='unique')
    op.drop_constraint('products_title_key', 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['code'])
    op.drop_column('products', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint('products_title_key', 'products', ['title'])
    op.create_unique_constraint('products_quantity_key', 'products', ['quantity'])
    op.drop_column('products', 'type')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###
